### ISSUE TITLE
Getters and Setters in an Interface

### ISSUE THREAD

**Issue by TomiEckert** [TomiEckert/SpaceStation#5]
There is a problem with **SpaceShip**.
Getters and setters are generally a really bad practice to put into interfaces, as might not want to make a specific field available for security concerns or something. I would change it for something else.

---

Some ideas:
- RedButton
- Unload
- Dock-Undock

Something like that.

**Comment by AmiChaib** [comment]
Oh yeah fixed that with my commit at least :3

**Comment by TomiEckert** [comment]
Noice
![image](https://user-images.githubusercontent.com/43214139/72302738-4c6f8900-366b-11ea-852b-3e68c8d7c09f.png)
