### ISSUE TITLE
No Astronaut array in Module

### ISSUE THREAD

**Issue by TomiEckert** [TomiEckert/SpaceStation#6]
**Module** abstract class has *addAstronaut* and *removeAstronaut*. But not an astronaut array.

Look for the *attachedModules* implementation, we can use the same principle in this case.

**Comment by AmiChaib** [comment]
wait addAstronaut and removeAstronaut are abstract methods, so you can only use it on a specific Module... just thought the abstract method should be there to indicate that that method needs to be implemented in each module. Idk help me understand

**Comment by TomiEckert** [comment]
[Here](https://github.com/TomiEckert/SpaceStation/compare/Dev?expand=1#diff-a80e26ba4fa9932a4ca78ee270e21851)
